import Head from 'next/head'

export default function _Head() {
  return(
    <Head>
      <title>Debi Vu</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}